### ISSUE TITLE
실행 환경 기재 요청

### ISSUE THREAD

**Issue by orchwang** [mskims/notion-ga#1]
Thank you for nice proxy server for notion users.
Could you describe environments like `Node version` or `Execute command`?
I think this will make it to use easier and broad for many users.

**Comment by mskims** [comment]
@hwangjongtaek Sure! will add the development guide soon. Thank you

**Comment by mskims** [comment]
Closing. Added at https://github.com/mskims/notion-ga/commit/b9253a430e132673b998dfbe8ab09748057e9aee
