### ISSUE TITLE
where

### ISSUE THREAD

**Issue by daledali** [mskims/notion-ga#3]
I put the server on a vm i have but how do i connect it to my notion?

**Comment by mskims** [comment]
Hi! Just replace hostname with your vm's hostname like below sample.

`https://notion-ga.ohwhos.now.sh/collect?tid=UA-97180334-1&host=mskim.me&page=/careers/product-designer`
⬇️ 
`http://YOUR_HOST_NAME/collect?tid=UA-97180334-1&host=mskim.me&page=/careers/product-designer`
